# Generated by Django 3.2.5 on 2021-07-26 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0004_alter_board_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_matrix_abbr',
            new_name='board_matrix',
        ),
        migrations.RemoveField(
            model_name='board',
            name='board_matrix_unicode',
        ),
        migrations.AlterField(
            model_name='board',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
